---
extends: "eslint:recommended"
rules:
  no-unused-vars: warn
  no-template-curly-in-string: error
  no-unsafe-negation: warn
  valid-jsdoc: error
  block-scoped-var: warn
  consistent-return: error
  curly: [error, multi-line, consistent]
  dot-location: [error, property]
  dot-notation: error
  eqeqeq: error
  no-console: warn
  no-empty: [error, {allowEmptyCatch: true}]
  no-extra-bind: error
  no-lone-blocks: error
  no-loop-func: warn
  no-multi-spaces: error
  no-new-func: error
  no-new: error
  no-param-reassign: error
  no-redeclare: [error, {builtinGlobals: true}]
  no-throw-literal: error
  no-unmodified-loop-condition: warn
  no-unused-expressions: warn
  no-useless-call: warn
  no-useless-concat: warn
  no-useless-escape: warn
  no-useless-return: warn
  no-void: error
  yoda: [error, never, {exceptRange: true}]
  strict: [error, never]
  no-catch-shadow: error
  no-delete-var: error
  no-label-var: error
  no-shadow: error
  no-shadow-restricted-names: warn
  no-undef-init: warn
  no-undef: warn
  no-undefined: error
  no-use-before-define: error
  callback-return: error
  no-mixed-requires: warn
  no-path-concat: error
  array-bracket-spacing: [warn, never]
  block-spacing: [warn, never]
  brace-style: [warn, 1tbs, {allowSingleLine: true}]
  camelcase: warn
  comma-dangle: [warn, never]
  comma-spacing: warn
  comma-style: [warn, last]
  computed-property-spacing: warn
  consistent-this: [error, that]
  eol-last: [error, always]
  func-call-spacing: warn
  func-name-matching: error
  indent: [warn, tab]
  key-spacing: warn
  keyword-spacing: warn
  line-comment-position: error
  linebreak-style: error
  lines-around-comment: warn
  new-cap: warn
  newline-per-chained-call: [warn, {ignoreChainWithDepth: 3}]
  no-lonely-if: error
  no-mixed-operators: warn
  no-multiple-empty-lines: [warn, {max: 1}]
  no-negated-condition: warn
  no-new-object: error
  no-array-constructor: error
  no-trailing-spaces: warn
  no-unneeded-ternary: error
  no-whitespace-before-property: warn
  object-curly-spacing: warn
  one-var-declaration-per-line: error
  operator-assignment: warn
  operator-linebreak: [warn, before]
  quotes: [warn, single, {avoidEscape: true, allowTemplateLiterals: true}]
  semi-spacing: warn
  semi: error
  space-before-function-paren: [warn, never]
  space-in-parens: warn
  space-infix-ops: warn
  space-unary-ops: warn
  spaced-comment: [warn]
  unicode-bom: error
  arrow-body-style: [warn, as-needed]
  arrow-parens: [warn, as-needed]
  arrow-spacing: warn
  generator-star-spacing: warn
  no-duplicate-imports: error
  no-useless-computed-key: error
  no-useless-constructor: warn
  no-var: error
  object-shorthand: error
  prefer-arrow-callback: error
  prefer-const: error
  prefer-numeric-literals: error
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: warn
  rest-spread-spacing: warn
  template-curly-spacing: warn
env:
  node: true
  es6: true
parserOptions:
  sourceType: module
